List<Map<String,dynamic>> singerList = [
  {
    "id":1,
    "image":"assets/images/arrijit.png",
  },
  {
    "id":2,
    "image":"assets/images/b.png",
  },
  {
    "id":3,
    "image":"assets/images/neha.png",
  },
  {
    "id":4,
    "image":"assets/images/shreya.png",
  },
  {
    "id":5,
    "image":"assets/images/tulsi.png",
  }
];
